contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nanopath channel"
    url: https://nfcore.slack.com/channels/nanopath
    about: Discussion about the nf-core/nanopath pipeline
